---
# This playbook deploys a simple standalone Tomcat 7 server.

- hosts: "{{ passed_in_hosts }}"
  remote_user: root
  become: yes
  become_method: sudo

  roles:
#    - selinux
    - tomcat
    - deploywar
